# fly.toml app configuration file generated for issue-backend on 2025-02-04T19:35:48+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'issue-backend'
primary_region = 'fra'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
