name = "issue_backend"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.49.0 and < 2.0.0"
wisp = ">= 1.4.0 and < 2.0.0"
mist = ">= 4.0.2 and < 5.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"
gleam_json = ">= 2.1.0 and < 3.0.0"
sqlight = ">= 0.9.1 and < 1.0.0"
gleam_http = ">= 3.7.2 and < 4.0.0"
aragorn2 = ">= 0.1.0 and < 1.0.0"
birl = ">= 1.8.0 and < 2.0.0"
gleam_crypto = ">= 1.4.0 and < 2.0.0"
bucket = ">= 1.2.0 and < 2.0.0"
dot_env = ">= 1.2.0 and < 2.0.0"
gleam_httpc = ">= 4.0.0 and < 5.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
