name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0"
          gleam-version: "1.6.3"
          rebar3-version: "3"
      - id: cache-gleam
        uses: actions/cache@v3
        with:
          path: build
          key: ${{runner.os}}-gleam-${{ hashFiles('manifest.toml')}}
      - if: ${{ !steps.cache-gleam.outputs.cache-hit }}
        run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
